#
# Juniper Olive - VM for netconf-checker commit checking juniper devices
#
# ge-0/0/0.0: management interface
# ge-0/0/1.0 - ge-0/0/7.0: user interfaces

Vagrant.configure(2) do |config|
  config.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"
 
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
    vb.gui = false
  end

  config.vm.define "olive1" do |olive1|
    olive1.vm.host_name = "olive1"
    olive1.vm.network "private_network",
                     ip: "10.99.12.2",
                     virtualbox__intnet: "1-2"
    olive1.vm.network "private_network",
                     ip: "10.99.13.2",
                     virtualbox__intnet: "1-3"
 # Make it clear we are pushing the ssh port from guest to default vagrant 2222 for host host_ip: "172.17.0.1",
    olive1.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
  end
end
